### ISSUE TITLE
KeyError: "['USD'] not found in axis"

### ISSUE THREAD

**Issue by mrfearless** [pxsocs/cryptoblotter#7] opened 2019-06-10 17:43 UTC
Installed and added first transaction, clicked on submit and got a crash

```
Traceback (most recent call last):
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "M:\PythonProjects\cryptoblotter\cryptoalpha\portfolio\routes.py", line 23, in portfolio_main

    portfolio_data, pie_data = generate_pos_table(user, "USD", False)
  File "M:\PythonProjects\cryptoblotter\cryptoalpha\users\utils.py", line 174, in generate_pos_table

    consol_table = consol_table.drop('USD')
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\frame.py", line 3940, in drop
    errors=errors)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\generic.py", line 3780, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\generic.py", line 3812, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\indexes\base.py", line
4965, in drop
    '{} not found in axis'.format(labels[mask]))
KeyError: "['USD'] not found in axis"
```

**Comment by pxsocs** [comment] 2019-06-10 18:00
I was able to replicate this error. This is happening when the first transaction included in the database was an "ASSET ONLY" Transaction. Can you confirm if that was the case?

**Comment by pxsocs** [comment] 2019-06-10 18:06
A fix was issued by changing `cryptoalpha\users\utils.py` under `generate_pos_table()` to handle the error: 
```
    try:
        consol_table = consol_table.drop('USD')
    except KeyError:
        logging.info("[generate_pos_table] No USD positions found")
```

Can you Git pull the new version and confirm if the error persists, please?

**Comment by mrfearless** [comment] 2019-06-11 08:55
I redid the installation and entered a single asset only trade. It did accept it and brought me to the main portfolio page. 

I noticed a few other issues though:

- Along the top of the page there is no menu bar like in the preview image, with Account Tools, Portfolio Actions, Portfolio Analysis, Other Tools, settings, logout buttons. I tried logging in via firefox 67.0.1 and chrome, but that menu bar is not visible on either.
- It seems to continually fetching from blockexplorer.com or showing `waiting for blockexplorer.com...` in the statusbar - although I see that has been raised in the issues #1.
- If i block blockexplorer.com with noscript extension then it seems to show `waiting 127.0.0.1...` in the statusbar.
- Few exceptions noted in the console:

```
IndexError: index out of bounds
Traceback (most recent call last):
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\indexes\base.py", line
4375, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas\_libs\index.pyx", line 81, in pandas._libs.index.IndexEngine.get_value

  File "pandas\_libs\index.pyx", line 89, in pandas._libs.index.IndexEngine.get_value

  File "pandas\_libs\index.pyx", line 447, in pandas._libs.index.DatetimeEngine.get_loc

  File "pandas\_libs\hashtable_class_helper.pxi", line 987, in pandas._libs.hashtable.Int64HashTable
.get_item

  File "pandas\_libs\hashtable_class_helper.pxi", line 993, in pandas._libs.hashtable.Int64HashTable
.get_item

KeyError: -7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1815, in full_d
ispatch_request
    rv = self.handle_user_exception(e)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "M:\PythonProjects\cryptoblotter\cryptoalpha\api\routes.py", line 192, in portstats
    meta['return_1wk'] = (meta['end_nav'] / data['NAV'][-7]) - 1
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\series.py", line 868, in __getitem__
    result = self.index.get_value(self, key)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\indexes\datetimes.py",
line 946, in get_value
    return com.maybe_box(self, Index.get_value(self, series, key),
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\indexes\base.py", line
4381, in get_value
    return libindex.get_value_box(s, key)
  File "pandas\_libs\index.pyx", line 52, in pandas._libs.index.get_value_box

  File "pandas\_libs\index.pyx", line 48, in pandas._libs.index.get_value_at

  File "pandas\_libs\util.pxd", line 113, in pandas._libs.util.get_value_at

  File "pandas\_libs\util.pxd", line 104, in pandas._libs.util.validate_indexer

IndexError: index out of bounds
Traceback (most recent call last):
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\indexes\base.py", line
4375, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas\_libs\index.pyx", line 81, in pandas._libs.index.IndexEngine.get_value

  File "pandas\_libs\index.pyx", line 89, in pandas._libs.index.IndexEngine.get_value

  File "pandas\_libs\index.pyx", line 447, in pandas._libs.index.DatetimeEngine.get_loc

  File "pandas\_libs\hashtable_class_helper.pxi", line 987, in pandas._libs.hashtable.Int64HashTable
.get_item

  File "pandas\_libs\hashtable_class_helper.pxi", line 993, in pandas._libs.hashtable.Int64HashTable
.get_item

KeyError: -7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1741, in handle
_exception
    reraise(exc_type, exc_value, tb)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1718, in handle
_user_exception
    reraise(exc_type, exc_value, tb)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask\app.py", line 1799, in dispat
ch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "M:\PythonProjects\cryptoblotter\cryptoalpha\api\routes.py", line 192, in portstats
    meta['return_1wk'] = (meta['end_nav'] / data['NAV'][-7]) - 1
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\series.py", line 868, in __getitem__
    result = self.index.get_value(self, key)
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\indexes\datetimes.py",
line 946, in get_value
    return com.maybe_box(self, Index.get_value(self, series, key),
  File "M:\PythonProjects\cryptoblotter\cb_env\lib\site-packages\pandas\core\indexes\base.py", line
4381, in get_value
    return libindex.get_value_box(s, key)
  File "pandas\_libs\index.pyx", line 52, in pandas._libs.index.get_value_box

  File "pandas\_libs\index.pyx", line 48, in pandas._libs.index.get_value_at

  File "pandas\_libs\util.pxd", line 113, in pandas._libs.util.get_value_at

  File "pandas\_libs\util.pxd", line 104, in pandas._libs.util.validate_indexer

IndexError: index out of bounds
```

**Comment by pxsocs** [comment] 2019-06-11 11:01
Thanks for reporting these. Addressing them separately below. 

- __Along the top of the page there is no menu bar like in the preview image, with Account Tools, Portfolio Actions, Portfolio Analysis, Other Tools, settings, logout buttons. I tried logging in via firefox 67.0.1 and chrome, but that menu bar is not visible on either.__
    -  That's odd and I haven't witnessed this behavior. On Chrome, can you:
        - Right click at the page and select __Inspect__
        - Verify on the `Console` under `errors`, if there are any errors related to Bootstrap or any mention of `layout.html`.
        - Under `Elements`, verify if the HTML for the header is present. Particularly the Navigation bar. Should start with: 
        ```
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        ```
        - Finally, can you navigate to [http://127.0.0.1:5000/about](http://127.0.0.1:5000/about) and confirm if the issue is present there as well.
        __I'm opening a new Issue for this specific topic - [please respond here](https://github.com/pxsocs/cryptoblotter/issues/9).__

- __It seems to continually fetching from blockexplorer.com or showing waiting for blockexplorer.com... in the statusbar - although I see that has been raised in the issues #1.__
    - Fixing this for next release, for some reason Blockexplorer's API stopped responding. I'm not a big fan of Blockexplorer anyway so looking for alternatives. 

- __Few exceptions noted in the console:__
    - These are all related and a fix have been issued for the next release. They happen when the portfolio is new and there's no historical NAV for 7 days, etc... 

I'm closing this Issue but opened one for the [missing navigation bar](https://github.com/pxsocs/cryptoblotter/issues/9).

**Closed by pxsocs** 2019-06-11 11:01 UTC
Labels: bug
